// Semana17Sesion01/d19423/culqi/front/src/components/CancelView.jsx
import React from 'react';

export default function CancelView({ onNavigate }) {
  return (
    <div className="feedback-view">
      <div className="feedback-icon cancel">
        <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><line x1="18" y1="6" x2="6" y2="18"/><line x1="6" y1="6" x2="18" y2="18"/></svg>
      </div>
      <h2 className="feedback-title">Pago Cancelado</h2>
      <p className="feedback-message">
        El proceso de compra fue interrumpido o cancelado. No se ha realizado ningún cargo a tu cuenta. Puedes volver a intentarlo cuando gustes.
      </p>
      
      <button onClick={() => onNavigate('catalog')} className="btn-secondary">
        Volver al Catálogo
      </button>
    </div>
  );
}

// Semana17Sesion01/d19423/stripe/front/src/components/CancelView.vue
<template>
  <div class="feedback-view">
    <div class="feedback-icon cancel">
      <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><line x1="18" y1="6" x2="6" y2="18"/><line x1="6" y1="6" x2="18" y2="18"/></svg>
    </div>
    <h2 class="feedback-title">Pago Cancelado</h2>
    <p class="feedback-message">
      El proceso de compra fue interrumpido o cancelado. No se ha realizado ningún cargo a tu cuenta. Puedes volver a intentarlo cuando gustes.
    </p>
    
    <button @click="$emit('navigate', 'catalog')" class="btn-secondary">
      Volver al Catálogo
    </button>
  </div>
</template>

<script setup>
defineEmits(['navigate']);
</script>
